use_frameworks!

target 'XHpodTest_Example' do
  pod 'XHpodTest', :path => '../XHpodTest.podspec'


  
  target 'XHpodTest_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'



  end
end
